branch: master
tagFormat: '${version}'

prepare:
- '@semantic-release/changelog'
- '@alorel-personal/semantic-release'
- &npm '@semantic-release/npm'
- path: &xc '@semantic-release/exec'
  cmd: yarn run alo copy-files
- path: *xc
  cmd: yarn run alo clean-dist
- path: *xc
  cmd: yarn run alo clean-pkg-json
- path: '@semantic-release/git'
  message: 'chore(release): ${nextRelease.version}'

publish:
  - path: *npm
    pkgRoot: './dist'
  - '@semantic-release/github'

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
