branch: master
tagFormat: '${version}'

pkgRoot: './dist'

prepare:
- '@semantic-release/changelog'
- '@alorel-personal/semantic-release'
- path: '@semantic-release/exec'
  cmd: yarn run alo copy-files
- '@semantic-release/npm'
- path: '@semantic-release/git'
  assets:
    - CHANGELOG.md
    - package.json
    - yarn.lock
    - README.md
  message: 'chore(release): ${nextRelease.version}'

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
