language: node_js
sudo: false
node_js:
- lts/carbon
- stable

before_install:
- npm i -g yarn greenkeeper-lockfile
- &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

install: yarn install --check-files --ignore-engines

script: yarn run tslint && yarn run build --noEmit && yarn test --forbid-only --forbid-pending

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

cache:
  yarn: true

stages:
- Test
- name: Release
  if: branch = master AND type = push AND (NOT tag IS present)

jobs:
  include:
  - stage: Release
    node_js: stable
    before_install:
    - npm i -g yarn
    - *prepKey
    before_script:
      - yarn run build
      - yarn run alo copy-files
      - yarn run alo clean-dist
      - yarn run alo clean-pkg-json
    script: semantic-release
    after_success: []
    after_script: []