language: node_js
node_js:
  - lts/dubnium
  - stable

before_install:
  - npm i -g yarn greenkeeper-lockfile@^2.0.0
  - greenkeeper-lockfile-update

install: yarn install --check-files --ignore-engines

script:
  - yarn run tslint
  - yarn run typecheck
  - if [[ $GH_TOKEN ]]; then yarn test --forbid-only --forbid-pending; else yarn test --forbid-only; fi;

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

before_cache: rm -rf ./node_modules/.cache
cache:
  yarn: true
  directories:
    - /home/travis/.cache/alobuild

stages:
  - Test
  - name: Release
    if: branch = master AND type = push AND (NOT tag IS present)

jobs:
  include:
    - stage: Release
      node_js: stable
      before_install: npm i -g yarn
      before_script:
        - yarn run build
        - ls dist -l
        - node dist/alo.js copy-files
      script: semantic-release
      after_success: []
      after_script: []
